version: "3"

services: 
  coin_auto_engine:
    image: python:3.8
    build:
      context: ..
      dockerfile: coin_auto/dockerfile
    container_name: coin_auto_engine
    volumes:
      - ../logs:/usr/src/app/logs/
    # command: python3 /usr/src/app/coin_auto.py -p 25 -w 1.5 -f 1.5
    command: python3 /usr/src/app/coin_auto.py -p 25 -d 2 -b 0.5
    environment:
      - "TZ=Asia/Seoul"